export type RegionId = 'france' | 'mediterranean' | 'north_europe' | 'north_america' | 'southern_hemisphere';

export type SeasonalEntry = { season: string; products: string[] };

export const REGIONS: { id: RegionId; name: string; flag: string }[] = [
  { id: 'france', name: 'France', flag: '🇫🇷' },
  { id: 'mediterranean', name: 'Mediterranean', flag: '🌊' },
  { id: 'north_europe', name: 'N. Europe', flag: '🇸🇪' },
  { id: 'north_america', name: 'N. America', flag: '🇺🇸' },
  { id: 'southern_hemisphere', name: 'S. Hemisphere', flag: '🌏' },
];

export const seasonalDataByRegion: Record<RegionId, Record<number, SeasonalEntry>> = {
  // Source: Greenpeace France seasonal calendar (greenpeace.fr/guetteur/calendrier)
  france: {
    1:  { season: 'Winter', products: ['Carrots', 'Leeks', 'Endives', 'Cabbage', 'Spinach', 'Apples', 'Pears', 'Clementines'] },
    2:  { season: 'Winter', products: ['Carrots', 'Leeks', 'Endives', 'Spinach', 'Radishes', 'Apples', 'Pears', 'Oranges'] },
    3:  { season: 'Spring', products: ['Asparagus', 'Leeks', 'Carrots', 'Spinach', 'Radishes', 'Apples', 'Pears', 'Oranges'] },
    4:  { season: 'Spring', products: ['Asparagus', 'Artichokes', 'Peas', 'Lettuce', 'Cauliflower', 'Radishes', 'Apples', 'Pears'] },
    5:  { season: 'Spring', products: ['Asparagus', 'Artichokes', 'Peas', 'Zucchini', 'Radishes', 'Strawberries', 'Cherries', 'Rhubarb'] },
    6:  { season: 'Summer', products: ['Artichokes', 'Zucchini', 'Cucumbers', 'Green beans', 'Fennel', 'Strawberries', 'Cherries', 'Apricots'] },
    7:  { season: 'Summer', products: ['Tomatoes', 'Zucchini', 'Eggplant', 'Peppers', 'Fennel', 'Raspberries', 'Peaches', 'Figs'] },
    8:  { season: 'Summer', products: ['Tomatoes', 'Peppers', 'Eggplant', 'Zucchini', 'Fennel', 'Peaches', 'Figs', 'Grapes'] },
    9:  { season: 'Autumn', products: ['Leeks', 'Fennel', 'Squash', 'Artichokes', 'Spinach', 'Apples', 'Pears', 'Grapes'] },
    10: { season: 'Autumn', products: ['Carrots', 'Leeks', 'Celeriac', 'Cabbage', 'Pumpkins', 'Chestnuts', 'Apples', 'Pears'] },
    11: { season: 'Autumn', products: ['Carrots', 'Leeks', 'Celeriac', 'Cabbage', 'Broccoli', 'Endives', 'Clementines', 'Apples'] },
    12: { season: 'Winter', products: ['Carrots', 'Leeks', 'Endives', 'Cabbage', 'Spinach', 'Clementines', 'Oranges', 'Pears'] },
  },
  mediterranean: {
    1:  { season: 'Winter', products: ['Citrus fruits', 'Artichokes', 'Broccoli', 'Fennel', 'Cauliflower', 'Olives'] },
    2:  { season: 'Winter', products: ['Citrus fruits', 'Artichokes', 'Fennel', 'Broccoli', 'Peas', 'Cauliflower'] },
    3:  { season: 'Spring', products: ['Artichokes', 'Peas', 'Fava beans', 'Asparagus', 'Strawberries', 'Fennel'] },
    4:  { season: 'Spring', products: ['Strawberries', 'Artichokes', 'Asparagus', 'Fava beans', 'Peas', 'Lettuce'] },
    5:  { season: 'Spring', products: ['Strawberries', 'Cherries', 'Zucchini', 'Tomatoes', 'Fava beans', 'Peaches'] },
    6:  { season: 'Summer', products: ['Tomatoes', 'Peppers', 'Zucchini', 'Peaches', 'Apricots', 'Cherries'] },
    7:  { season: 'Summer', products: ['Tomatoes', 'Peppers', 'Eggplant', 'Watermelon', 'Peaches', 'Figs'] },
    8:  { season: 'Summer', products: ['Tomatoes', 'Peppers', 'Eggplant', 'Figs', 'Grapes', 'Watermelon'] },
    9:  { season: 'Autumn', products: ['Grapes', 'Figs', 'Tomatoes', 'Eggplant', 'Peppers', 'Mushrooms'] },
    10: { season: 'Autumn', products: ['Grapes', 'Pomegranates', 'Mushrooms', 'Chestnuts', 'Artichokes', 'Fennel'] },
    11: { season: 'Autumn', products: ['Citrus fruits', 'Artichokes', 'Broccoli', 'Fennel', 'Mushrooms', 'Olives'] },
    12: { season: 'Winter', products: ['Citrus fruits', 'Artichokes', 'Broccoli', 'Cauliflower', 'Fennel', 'Olives'] },
  },
  north_europe: {
    1:  { season: 'Winter', products: ['Kale', 'Carrots', 'Potatoes', 'Parsnips', 'Beetroot', 'Cabbage'] },
    2:  { season: 'Winter', products: ['Kale', 'Carrots', 'Leeks', 'Potatoes', 'Parsnips', 'Celeriac'] },
    3:  { season: 'Winter', products: ['Kale', 'Leeks', 'Carrots', 'Potatoes', 'Broccoli', 'Celeriac'] },
    4:  { season: 'Spring', products: ['Asparagus', 'Broccoli', 'Spinach', 'Radishes', 'Lettuce', 'Leeks'] },
    5:  { season: 'Spring', products: ['Asparagus', 'Spinach', 'Radishes', 'Lettuce', 'Strawberries', 'Peas'] },
    6:  { season: 'Summer', products: ['Strawberries', 'Peas', 'Lettuce', 'Broad beans', 'New potatoes', 'Raspberries'] },
    7:  { season: 'Summer', products: ['Strawberries', 'Raspberries', 'Peas', 'Zucchini', 'Broad beans', 'Lettuce'] },
    8:  { season: 'Summer', products: ['Tomatoes', 'Zucchini', 'Runner beans', 'Blueberries', 'Corn', 'Cucumbers'] },
    9:  { season: 'Autumn', products: ['Apples', 'Pears', 'Blackberries', 'Mushrooms', 'Squash', 'Beetroot'] },
    10: { season: 'Autumn', products: ['Apples', 'Pears', 'Kale', 'Mushrooms', 'Squash', 'Beetroot'] },
    11: { season: 'Autumn', products: ['Kale', 'Parsnips', 'Carrots', 'Potatoes', 'Brussels sprouts', 'Leeks'] },
    12: { season: 'Winter', products: ['Kale', 'Brussels sprouts', 'Parsnips', 'Carrots', 'Potatoes', 'Celeriac'] },
  },
  north_america: {
    1:  { season: 'Winter', products: ['Citrus fruits', 'Kale', 'Brussels sprouts', 'Sweet potatoes', 'Carrots', 'Beets'] },
    2:  { season: 'Winter', products: ['Citrus fruits', 'Kale', 'Leeks', 'Sweet potatoes', 'Carrots', 'Beets'] },
    3:  { season: 'Spring', products: ['Asparagus', 'Artichokes', 'Spinach', 'Lettuce', 'Radishes', 'Peas'] },
    4:  { season: 'Spring', products: ['Asparagus', 'Peas', 'Strawberries', 'Lettuce', 'Artichokes', 'Radishes'] },
    5:  { season: 'Spring', products: ['Strawberries', 'Asparagus', 'Peas', 'Lettuce', 'Cherries', 'Radishes'] },
    6:  { season: 'Summer', products: ['Blueberries', 'Cherries', 'Tomatoes', 'Zucchini', 'Corn', 'Peaches'] },
    7:  { season: 'Summer', products: ['Tomatoes', 'Corn', 'Peaches', 'Blueberries', 'Peppers', 'Zucchini'] },
    8:  { season: 'Summer', products: ['Tomatoes', 'Corn', 'Peaches', 'Plums', 'Melons', 'Peppers'] },
    9:  { season: 'Autumn', products: ['Apples', 'Grapes', 'Pears', 'Pumpkins', 'Squash', 'Sweet potatoes'] },
    10: { season: 'Autumn', products: ['Apples', 'Pears', 'Pumpkins', 'Sweet potatoes', 'Cranberries', 'Mushrooms'] },
    11: { season: 'Autumn', products: ['Sweet potatoes', 'Kale', 'Brussels sprouts', 'Apples', 'Cranberries', 'Pears'] },
    12: { season: 'Winter', products: ['Citrus fruits', 'Kale', 'Sweet potatoes', 'Brussels sprouts', 'Pomegranates', 'Carrots'] },
  },
  southern_hemisphere: {
    1:  { season: 'Summer', products: ['Tomatoes', 'Zucchini', 'Cucumbers', 'Peaches', 'Cherries', 'Corn'] },
    2:  { season: 'Summer', products: ['Tomatoes', 'Peppers', 'Eggplant', 'Peaches', 'Plums', 'Melons'] },
    3:  { season: 'Autumn', products: ['Grapes', 'Apples', 'Pears', 'Tomatoes', 'Peppers', 'Figs'] },
    4:  { season: 'Autumn', products: ['Apples', 'Pears', 'Grapes', 'Mushrooms', 'Pumpkins', 'Squash'] },
    5:  { season: 'Autumn', products: ['Apples', 'Pears', 'Cabbage', 'Carrots', 'Potatoes', 'Citrus fruits'] },
    6:  { season: 'Winter', products: ['Citrus fruits', 'Cabbage', 'Carrots', 'Potatoes', 'Leeks', 'Broccoli'] },
    7:  { season: 'Winter', products: ['Citrus fruits', 'Cabbage', 'Kale', 'Carrots', 'Potatoes', 'Cauliflower'] },
    8:  { season: 'Winter', products: ['Citrus fruits', 'Broccoli', 'Cauliflower', 'Leeks', 'Carrots', 'Kale'] },
    9:  { season: 'Spring', products: ['Asparagus', 'Strawberries', 'Peas', 'Lettuce', 'Radishes', 'Spinach'] },
    10: { season: 'Spring', products: ['Strawberries', 'Asparagus', 'Cherries', 'Peas', 'Lettuce', 'Artichokes'] },
    11: { season: 'Spring', products: ['Strawberries', 'Cherries', 'Tomatoes', 'Zucchini', 'Peaches', 'Asparagus'] },
    12: { season: 'Summer', products: ['Tomatoes', 'Zucchini', 'Cucumbers', 'Peaches', 'Cherries', 'Melons'] },
  },
};

export const productEmojiMap: Record<string, string> = {
  'Citrus fruits': '🍊',
  'Cabbage': '🥬',
  'Carrots': '🥕',
  'Potatoes': '🥔',
  'Apples': '🍎',
  'Pears': '🍐',
  'Leeks': '🧅',
  'Asparagus': '🌱',
  'Spinach': '🥬',
  'Lettuce': '🥬',
  'Radishes': '🌶️',
  'Strawberries': '🍓',
  'Peas': '🫛',
  'Artichokes': '🌿',
  'Cherries': '🍒',
  'Tomatoes': '🍅',
  'Zucchini': '🥒',
  'Cucumbers': '🥒',
  'Peaches': '🍑',
  'Peppers': '🫑',
  'Plums': '🟣',
  'Blueberries': '🫐',
  'Corn': '🌽',
  'Melons': '🍈',
  'Grapes': '🍇',
  'Mushrooms': '🍄',
  'Pumpkins': '🎃',
  'Squash': '🎃',
  'Chestnuts': '🌰',
  'Brussels sprouts': '🥦',
  'Endives': '🥬',
  'Figs': '🍈',
  'Broccoli': '🥦',
  'Cauliflower': '🥦',
  'Fennel': '🌿',
  'Olives': '🫒',
  'Fava beans': '🫘',
  'Apricots': '🍑',
  'Eggplant': '🍆',
  'Watermelon': '🍉',
  'Pomegranates': '🍎',
  'Kale': '🥬',
  'Parsnips': '🥕',
  'Beetroot': '🥕',
  'Beets': '🥕',
  'Celeriac': '🥔',
  'Broad beans': '🫛',
  'Raspberries': '🍓',
  'Runner beans': '🫛',
  'Blackberries': '🫐',
  'New potatoes': '🥔',
  'Sweet potatoes': '🍠',
  'Cranberries': '🍒',
  'Clementines': '🍊',
  'Oranges': '🍊',
  'Green beans': '🫘',
  'Rhubarb': '🌿',
  'Quince': '🍐',
};
